"""add role to user

Revision ID: 36f364a4c344
Revises: 78c97137cb96
Create Date: 2025-06-05 17:36:20.692773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f364a4c344'
down_revision: Union[str, None] = '78c97137cb96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1️⃣  Ajouter la colonne EN ACCEPTANT les NULL
    op.add_column(
        "user",
        sa.Column("role",
                  sa.Enum("admin", "user", name="userrole"),
                  nullable=True)
    )

    # 2️⃣  Mettre une valeur pour les lignes existantes
    op.execute('UPDATE "user" SET role = \'user\' WHERE role IS NULL')

    # 3️⃣  Rendre la colonne obligatoire
    op.alter_column("user", "role", nullable=False)

    # --------- même problème pour is_active ----------
    op.add_column(
        "user",
        sa.Column("is_active", sa.Boolean(), nullable=True)
    )
    op.execute('UPDATE "user" SET is_active = TRUE WHERE is_active IS NULL')
    op.alter_column("user", "is_active", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
